
[general]
	#Shows a message in chat warning the player that the mod is early in development
	showBetaWelcomeMessage = true

[updates]
	#  BUTTON: In the exit confirm screen
	searchForUnstable = true
	#Search for updates on startup.
	searchOnStartup = false

[machine]

	[machine.fluidGenerators]
		#The amount of fluid (in milliBuckets, or mB) fluid generators consume at once.
		#Lower values reduce waste, but may cause lag as the generator more frequently turns on/off.
		#A generator with less fluid in the tank will not be able to run.
		#Range: 1 ~ 1000
		injectionVolume = 100

[world]

	[world.oilLake]
		#Chance of oil lakes spawning (1 in chance). Higher numbers = less common. Set 0 to disable.
		#Water is 4, lava is 80. Oil lakes will spawn underground about 90% of the time.
		#Note that disabling oil will make some items uncraftable unless recipes are changed
		#Range: > 0
		chance = 6

